services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: unless-stopped

volumes:
  postgres_data: